name: flutter_boilerplate_project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  flutter_approuter: ^3.0.1
  flutter_logger_plus: ^1.0.1
  flutter_encrypt_plus: ^2.0.0
  dio: ^5.2.1+1
  dio_smart_retry: ^5.0.0
  restart_app: ^1.2.1
  get_it: ^7.6.0

  # Class Generator
  freezed_annotation: any
  internet_connection_checker: ^1.0.0+1
  flutter_displaymode: ^0.6.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Class Generator
  build_runner: any
  json_serializable: any
  freezed: any

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
